### PR TITLE
replace gptel with llm

### PR DESCRIPTION
**Pull request by avishefi**
To discuss the idea of replacing `gptel` with `llm`.

### CODE REVIEW

**Comment by avishefi** [comment]
Example setup:

```emacs-lisp
(setq magit-gptcommit-llm-provider (make-llm-openai :key my-openai-key))
```

**Comment by douo** [comment]
Awesome! Thank you so much. I will test it out as soon as possible.

**Comment by avishefi** [comment]
Great. I left out partial streaming updates for the time being so we can evaluate if this is the direction.

**Comment by roychri** [comment]
Works very well for me, even with gpt-4o! Good job!

**Comment by perweij** [comment]
Nice, thanks! 

I can get it to generate a commit message which appears under "GPT commit: Done" in the magit-status buffer, but it seems I can't get the extra GPT commit options in the commit menu (screenshot from the nice demo video), so for now I'll manually copy the message from the magit-status buffer into the commit message buffer.

image

**Comment by avishefi** [comment]
@perweij Yes, this is a rough sketch to get @douo's feedback, there are still details to sort out.

**Comment by jave** [comment]
this branch works well for me, and the main branch doesnt work.
So it would be nice if it could be merged to main.

**Comment by avishefi** [comment]
I'll try to sort out what's left and then we'll have to wait to @douo's feedback.

**Comment by douo** [comment]
Sorry for the late reply; I had a test a few weeks ago. I am using a third-party OpenAI capacity server. When using llm.el 0.13, I encountered an error while parsing the response. This issue still persists in llm.el 0.16.1. I believe this is a bug in llm.el.

Additionally, I tested this PR with Gemini, and it worked well. I believe integrating magit-gptcommit--stream-insert-response (if I remember correctly) into partial-callback will make this PR ready to merge.

**Comment by avishefi** [comment]
I also fixed a few bugs related to error handling, please test and let me know if there are other issues.

**Comment by douo** [comment]
Work like a charm. Thank you so much.

**Pull request merged**
